# ----- Basics --------------

# enable mouse support
set -g mouse on

# Use wider color palette
set -g default-terminal screen-256color

# Sets parent terminal title to same as current tmux window
set -g set-titles on
set -g set-titles-string "#I - #W"

# ----- Navigation ----------

# Allow Alt + Arrow to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch Windows with Ctrl + Alt + Arrow
bind -n C-M-Right next-window
bind -n C-M-Left previous-window

# pane splitting binds
# v adds horizontal and h vertical split
bind v split-window -v
bind h split-window -h

# ----- Plugins -------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# ----- Themes -------------

# catppuccin
run "$XDG_CONFIG_HOME/tmux/plugins/catppuccin/tmux/catppuccin.tmux"

# rose-pine
# set -g @plugin 'rose-pine/tmux'
# source "$XDG_CONFIG_HOME/tmux/rose_pine.conf"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$XDG_CONFIG_HOME/tmux/tpm/tpm"
