# ----- Basics ---------

# enable mouse support
set -g mouse on

# Use wider color palette
set -g default-terminal screen-256color

# Sets parent terminal title to same as current tmux window
set -g set-titles on
set -g set-titles-string "#I:#W"

# ----- Navigation -----

# Allow Alt+Arrow  to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# pane splitting binds
# v adds horizontal and h vertical split
bind v split-window -v
bind h split-window -h


# ----- Status Bar -----
# purple bar
set -g status-bg colour54
# white text
set -g status-fg colour7
