[[language]]
name = "bash"
auto-format = true
# 2 space indent, indent cases in switch
formatter = { command = "shfmt", args = ["-i", "2", "-ci"] }
language-servers = ["bash-language-server"]

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",  # optional
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = [
  "vscode-html-language-server",
  "superhtml",
]
[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
language-servers = ["marksman"]

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/full/path/to/node_modules/@vue/typescript-plugin"
languages = ["vue"]
