# theme = "dark_plus"
theme = "rose_pine"

[editor]
line-number = "relative"
cursorline = true
true-color = true
color-modes = true
scrolloff = 8
idle-timeout = 0
bufferline = "multiple"
popup-border = "all"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"  # show warnings and errors on the cursorline inline

[editor.smart-tab]
supersede-menu = true

[keys.insert]
# move lines with alt up/down
A-down = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "move_line_down"
]
A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "move_line_up"
]

"C-left" = "move_prev_long_word_start"
"C-right" = "move_next_long_word_start"

# duplicate line and save into d register
# (avoids cluttering default register)
C-d = '@X"dy"dp'

# movement
C-end = "goto_file_end"
C-home = "goto_file_start"

[keys.normal]
# switch between buffers
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"

# format file
"S-A-f" = "@:format<ret>"

C-d = '@X"dy"dp'

# movement
C-end = "goto_file_end"
C-home = "goto_file_start"

[keys.normal.backspace]
w = ":write-all"
r = [":reload-all", ":config-reload"]

# lf
f = [
  ":write-all",
  ":insert-output lf >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]

# ------ Git ------------
[keys.normal.backspace.g]
# open Lazygit
o = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]

# inline blame
b = ":run-shell-command ~/.config/helix/utils/blame_line_pretty.sh %{buffer_name} %{cursor_line}"

# # full last commit in the line changes for the file
B = ":open %sh{~/.config/helix/utils/blame_file_pretty.sh %{buffer_name} %{cursor_line}}"

# yazi
[keys.normal.space]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file-h21a434',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
